function G = group_closure(gens, N)
%GROUP_CLOSURE  Generate a permutation group from generators (Dimino's algorithm).
%
%   G = GROUP_CLOSURE(GENS, N) takes generator permutations of N lattice
%   sites and returns a struct describing the full group <GENS>.
%
%   INPUT
%     GENS : generators given as one of
%              - a cell array of 1xN permutation vectors,
%              - an MxN matrix whose rows are permutation vectors, or
%              - a single 1xN permutation vector.
%            A permutation P is stored as a vector with P(i) = image of site i.
%            Group multiplication is function composition,
%                (A*B)(i) = A(B(i)),   in MATLAB simply  A(B).
%     N    : number of lattice sites (length of each permutation).
%
%   OUTPUT  (struct G)
%     G.N          number of sites
%     G.n          group order |G|
%     G.elements   n x N matrix, row k is the k-th group element
%     G.gens       cell array of the (normalised) generators
%     G.multtab    n x n table, G.multtab(a,b) = index of element A*B
%     G.inv        1 x n vector, G.inv(a) = index of the inverse of element a
%     G.id         index of the identity element (always 1)
%     G.classes    cell array, each cell holds the indices of a conjugacy class
%     G.classReps  1 x nc representative index of each conjugacy class
%     G.classSizes 1 x nc sizes of the conjugacy classes
%
%   METHOD
%     Dimino's algorithm builds the group as a disjoint union of cosets of the
%     subgroup generated by the already-processed generators: it repeatedly
%     multiplies in the next generator and closes the resulting cosets until
%     the set is stable.  Closure is verified explicitly at the end.
%
%   PROVENANCE
%     Vendored verbatim (body unchanged) from the standalone toolbox in
%     symmetry_generation/group_closure.m so the FTLM pipeline can build a group
%     from user-supplied permutation generators WITHOUT putting the toolbox
%     folder on the MATLAB path (that folder ships its own realify_irreps.m with
%     a different signature, which would shadow the project root realify_irreps).
%     See GROUP_FROM_GENERATORS for the adapter that maps this struct onto the
%     FTLM provider contract (icosahedron_Ih_full / square_lattice_spacegroup).
%
%   See also GROUP_FROM_GENERATORS, IRREPS_FROM_GROUP, REALIFY_IRREPS,
%            SQUARE_LATTICE_SPACEGROUP.

% ================================================================
% Copyright 2026 Shadan Ghassemi Tabrizi, Technische Universitaet Dresden,
% and Helmholtz-Zentrum Dresden-Rossendorf e.V.
% Licensed under the Apache License, Version 2.0.
% ================================================================

    % --- normalise generators to a cell array of row vectors ---
    if iscell(gens)
        gc = cellfun(@(v) v(:).', gens, 'UniformOutput', false);
    elseif isvector(gens)
        gc = { gens(:).' };
    else
        gc = num2cell(gens, 2);
        gc = cellfun(@(v) v(:).', gc, 'UniformOutput', false);
    end
    ngen = numel(gc);

    id    = 1:N;
    keyof = @(p) sprintf('%d,', p);          % unique string key for a permutation

    % element store + hash map (key -> row index)
    E   = id;
    map = containers.Map('KeyType', 'char', 'ValueType', 'double');
    map(keyof(id)) = 1;
    cnt = 1;

    % --- Dimino step 1: cyclic subgroup of the first generator ---
    g1 = gc{1};
    g  = g1;
    while ~isequal(g, id)
        cnt = cnt + 1;  E(cnt, :) = g;  map(keyof(g)) = cnt;
        g = g(g1);                            % g <- g * g1
    end

    % --- Dimino step 2: fold in the remaining generators ---
    for s = 2:ngen
        gs = gc{s};
        if ~isKey(map, keyof(gs))
            prevord = cnt;                    % order of subgroup so far
            % append the coset  (old subgroup) * gs
            cnt = cnt + 1;  E(cnt, :) = gs;  map(keyof(gs)) = cnt;   % id*gs
            for j = 2:prevord
                ej = E(j, :);  ej = ej(gs);
                cnt = cnt + 1;  E(cnt, :) = ej;  map(keyof(ej)) = cnt;
            end
            rep = prevord + 1;                % first new coset representative
            while rep <= cnt
                for t = 1:s
                    gt = gc{t};
                    x = E(rep, :);  x = x(gt);        % rep * gt
                    if ~isKey(map, keyof(x))
                        cnt = cnt + 1;  E(cnt, :) = x;  map(keyof(x)) = cnt;
                        for j = 2:prevord
                            ej = E(j, :);  ej = ej(x);
                            cnt = cnt + 1;  E(cnt, :) = ej;  map(keyof(ej)) = cnt;
                        end
                    end
                end
                rep = rep + prevord;
            end
        end
    end
    n = cnt;

    % --- multiplication table and inverses ---
    multtab = zeros(n, n);
    for a = 1:n
        Ea = E(a, :);
        for b = 1:n
            p = Ea(E(b, :));                  % A*B = A(B)
            multtab(a, b) = map(keyof(p));
        end
    end
    invv = zeros(1, n);
    for a = 1:n
        [~, q] = sort(E(a, :));               % inverse permutation
        invv(a) = map(keyof(q));
    end

    % --- closure self-check (safety net) ---
    if any(multtab(:) < 1) || numel(unique(multtab(:))) ~= n
        error('group_closure:notClosed', ...
              'Generated set is not closed -- check the generators.');
    end

    % --- conjugacy classes ---
    assigned = false(1, n);
    classes  = {};
    for a = 1:n
        if ~assigned(a)
            orb = zeros(1, n);  m = 0;
            for gi = 1:n
                b = multtab(multtab(gi, a), invv(gi));   % g * a * g^{-1}
                if ~assigned(b)
                    assigned(b) = true;  m = m + 1;  orb(m) = b;
                end
            end
            classes{end+1} = sort(orb(1:m)); %#ok<AGROW>
        end
    end
    classReps  = cellfun(@(c) c(1), classes);
    classSizes = cellfun(@numel, classes);

    % --- pack output ---
    G = struct();
    G.N = N;  G.n = n;  G.elements = E;  G.gens = gc;
    G.multtab = multtab;  G.inv = invv;  G.id = 1;
    G.classes = classes;  G.classReps = classReps;  G.classSizes = classSizes;
end
