function group = square_lattice_spacegroup(Lx, Ly)
%SQUARE_LATTICE_SPACEGROUP  Full space group of the Lx x Ly periodic square
%                           lattice as a site-permutation group.
%
%   GROUP = SQUARE_LATTICE_SPACEGROUP(LX, LY) returns the symmetry group of
%   the Lx x Ly torus generated by the lattice translations C_Lx x C_Ly
%   together with the site point group about the origin:
%       - C_4v (order 8) if LX == LY (square): 4 rotations + 4 mirrors;
%       - C_2v (order 4) otherwise (rectangular): {E, C_2, sigma_x, sigma_y}.
%   The total order is  Lx*Ly * |P|  (= 8*L^2 for a square L x L lattice).
%
%   This is the NON-ABELIAN generalisation of SQUARE_LATTICE_TRANSLATION_GROUP
%   (which is the translation subgroup only). It is built purely as a
%   permutation group on the N = Lx*Ly sites; the irreducible representations
%   (needed by the FTLM pipeline) are added separately by the little-group /
%   induced-representation construction. min_image_Ih / enumerate / collect
%   already consume this struct generically (they use only perms/order/identity).
%
%   Site labelling: site (x, y), x = 0..Lx-1, y = 0..Ly-1, index
%       i = 1 + x + Lx*y   (same as SQUARE_LATTICE_TRANSLATION_GROUP).
%   Permutation convention: perms(k, i) = j means site i is sent to site j by
%   group element k (same as ICOSAHEDRON_IH_FULL / APPLY_PERM_TO_STATE).
%
%   Output struct fields:
%       N, order        number of sites / group order
%       Lx, Ly          lattice extents
%       point_group     'C_4v' or 'C_2v'
%       perms           [order x N] double site permutations
%       perm_mats       [N x N x order] permutation matrices (P(a,b)=1 iff b->a)
%       inv             [order x 1] int32 inverse index
%       mul             [order x order] int32 multiplication table (g(a)*g(b))
%       identity        int32 identity index
%       class_idx       [order x 1] int32 conjugacy-class index
%       class_size      [n_class x 1] int32
%       gens            indices of the generating elements
%
%   See also SQUARE_LATTICE_TRANSLATION_GROUP, ICOSAHEDRON_IH_FULL,
%            MIN_IMAGE_IH, TEST_SQUARE_LATTICE_SPACEGROUP.

% ================================================================
% Copyright 2026 Shadan Ghassemi Tabrizi, Technische Universitaet Dresden,
% and Helmholtz-Zentrum Dresden-Rossendorf e.V.
% Licensed under the Apache License, Version 2.0.
% ================================================================

    assert(isscalar(Lx) && Lx >= 2 && Lx == round(Lx), 'Lx must be an integer >= 2');
    assert(isscalar(Ly) && Ly >= 2 && Ly == round(Ly), 'Ly must be an integer >= 2');

    N        = Lx * Ly;
    is_square = (Lx == Ly);
    pg_order = 4 + 4 * is_square;        % C_2v = 4, C_4v = 8
    expected = N * pg_order;

    %% Generator permutations (1-based site permutations on the torus).
    gens_perm = { pg_perm(@(x,y) x+1, @(x,y)  y , Lx, Ly), ...   % t_x
                  pg_perm(@(x,y)  x , @(x,y) y+1, Lx, Ly), ...   % t_y
                  pg_perm(@(x,y) -x , @(x,y)  y , Lx, Ly), ...   % sigma_y (x -> -x)
                  pg_perm(@(x,y)  x , @(x,y) -y , Lx, Ly) };     % sigma_x (y -> -y)
    if is_square
        gens_perm{end+1} = pg_perm(@(x,y) -y, @(x,y) x, Lx, Ly); % C_4: (x,y) -> (-y, x)
    end

    %% BFS closure under the generators -> the full set of site permutations.
    key_of  = @(p) sprintf('%d,', p);
    id_row  = 1 : N;
    seen    = containers.Map('KeyType', 'char', 'ValueType', 'double');
    perms   = id_row;                       % start from the identity
    seen(key_of(id_row)) = 1;
    frontier = 1;
    while ~isempty(frontier)
        next = [];
        for fi = 1 : numel(frontier)
            pa = perms(frontier(fi), :);
            for gi = 1 : numel(gens_perm)
                pg = gens_perm{gi};
                pc = pa(pg);                % composition: (a o g)(i) = a(g(i))
                k  = key_of(pc);
                if ~isKey(seen, k)
                    perms(end+1, :) = pc;            %#ok<AGROW>
                    seen(k) = size(perms, 1);
                    next(end+1) = size(perms, 1);    %#ok<AGROW>
                end
            end
        end
        frontier = next;
    end
    order = size(perms, 1);
    assert(order == expected, ...
        'square_lattice_spacegroup: closure gave order %d, expected %d', order, expected);

    %% Multiplication table, inverses (composition (g h)(v) = g(h(v))).
    mul = zeros(order, order, 'int32');
    for a = 1 : order
        pa = perms(a, :);
        for b = 1 : order
            mul(a, b) = int32(seen(key_of(pa(perms(b, :)))));
        end
    end
    identity = seen(key_of(id_row));
    inv_idx  = zeros(order, 1, 'int32');
    for k = 1 : order
        pk = perms(k, :);
        pinv = zeros(1, N);
        pinv(pk) = 1 : N;
        inv_idx(k) = int32(seen(key_of(pinv)));
    end
    assert(all(arrayfun(@(k) mul(k, inv_idx(k)) == identity, 1:order)), ...
        'inverse table sanity failed');

    %% Conjugacy classes.
    assigned = zeros(order, 1, 'int32');
    classes  = {};
    for i = 1 : order
        if assigned(i) > 0, continue; end
        cls = false(order, 1);
        for h = 1 : order
            cls(mul(h, mul(i, inv_idx(h)))) = true;
        end
        classes{end+1, 1} = find(cls);          %#ok<AGROW>
        assigned(classes{end}) = numel(classes);
    end

    %% Permutation matrices (P(a,b)=1 iff b -> a, i.e. a = perms(k,b)).
    perm_mats = zeros(N, N, order);
    for k = 1 : order
        for b = 1 : N
            perm_mats(perms(k, b), b, k) = 1;
        end
    end

    %% Pack.
    group.N           = N;
    group.order       = order;
    group.Lx          = Lx;
    group.Ly          = Ly;
    group.point_group = ternary(is_square, 'C_4v', 'C_2v');
    group.perms       = perms;
    group.perm_mats   = perm_mats;
    group.inv         = inv_idx;
    group.mul         = mul;
    group.identity    = int32(identity);
    group.class_idx   = assigned;
    group.class_size  = int32(cellfun(@numel, classes));
    group.n_class     = numel(classes);
end

% ----------------------------------------------------------------
function p = pg_perm(fx, fy, Lx, Ly)
%PG_PERM  Site permutation from coordinate maps fx,fy: (x,y) -> (fx,fy) mod L.
    p = zeros(1, Lx * Ly);
    for y = 0 : Ly - 1
        for x = 0 : Lx - 1
            xp = mod(fx(x, y), Lx);
            yp = mod(fy(x, y), Ly);
            p(1 + x + Lx * y) = 1 + xp + Lx * yp;
        end
    end
end

function s = ternary(c, a, b)
    if c, s = a; else, s = b; end
end
