%% demo.m -- D6 ring (N=6): group, irreps, SALCs, block-diagonal Heisenberg H
%
% Builds the dihedral group D6 (|G| = 12) generated by translation and
% reflection of a 6-site ring, computes its irreducible representations by
% Dixon's method, constructs the symmetry-adapted basis of the 2^6 spin-1/2
% space, and shows that the Heisenberg Hamiltonian H = sum_<i,j> S_i.S_j is
% block diagonal in that basis.

clear; clc;

% --- input: lattice size and generators (change freely) ---
N    = 6;
T    = [2 3 4 5 6 1];          % translation  (site i -> i+1)
R    = [6 5 4 3 2 1];          % reflection   (site i -> N+1-i)
gens = {T, R};

%% 1) group closure
G = group_closure(gens, N);
fprintf('Group order |G|              = %d\n', G.n);
fprintf('Number of conjugacy classes = %d\n', numel(G.classes));

%% 2) irreducible representations (Dixon)
[irreps, info] = dixon_irreps(G, 42, 1e-10);
fprintf('\nIrrep dimensions : %s\n', mat2str(info.dims));
fprintf('sum(d_a^2)       = %d   (should equal |G| = %d)\n', ...
        sum(info.dims.^2), G.n);

fprintf('\nCharacter table (rows = irreps, cols = conjugacy classes):\n');
ct = info.chartable;
if max(abs(imag(ct(:)))) < 1e-9, ct = real(ct); end
disp(round(ct * 1e6) / 1e6);
fprintf('Class sizes : %s\n', mat2str(info.classSizes));

%% 3) SALCs on the 2^N spin space
S = salc_projectors(irreps, G, N, 1e-10);
fprintf('\nMultiplicities m_a in 2^%d space : %s\n', N, mat2str(S.mult));
fprintf('Isotypic sector dims d_a*m_a    : %s\n', mat2str(S.sectordim));
fprintf('sum(sector dims) = %d   (should equal 2^%d = %d)\n', ...
        sum(S.sectordim), N, 2^N);

%% 4) Heisenberg Hamiltonian and block diagonalisation
H  = heisenberg_ring(N);
Hs = S.U' * H * S.U;
Hs(abs(Hs) < 1e-10) = 0;

[P, Q]  = ndgrid(S.blockId, S.blockId);
offmask = (P ~= Q);
leak    = max([abs(Hs(offmask)); 0]);
fprintf('\nMax off-block element of H in SALC basis = %.3e\n', leak);

cmax = 0;
for a = 1:numel(S.Piso)
    cmax = max(cmax, max(max(abs(S.Piso{a} * H - H * S.Piso{a}))));
end
fprintf('Max |[P_a, H]|                           = %.3e\n', full(cmax));

%% block structure listing
fprintf('\nBlock structure (irrep, partner, size):\n');
for b = 1:numel(S.blocks)
    bl = S.blocks(b);
    fprintf('  block %2d: irrep %d  partner %d  size %d\n', ...
            b, bl.alpha, bl.i, bl.mult);
end

%% visualise block structure
try
    f = figure('Name', 'Heisenberg H in SALC basis', 'Visible', 'off');
    subplot(1, 2, 1); spy(abs(H)  > 1e-12);  title('H in product basis');
    subplot(1, 2, 2); spy(abs(Hs) > 1e-10);  title('H in SALC basis');
    drawnow;
    saveas(f, 'H_blockstructure.png');
    fprintf('\nSaved block-structure figure to H_blockstructure.png\n');
catch ME
    fprintf('\n(Plotting skipped: %s)\n', ME.message);
end
